server:
  port: 8082
  servlet:
    context-path: /imsystem
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://121.199.10.4:3306/emm_im?useUnicode=true&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mchange.v2.c3p0.ComboPooledDataSource

  redis:
    #redis 服务器地址
    host: 127.0.0.1
    #redis端口
    port: 6379
    #redis 密码
#    password: vRKqbKQKhcZrokNeWrfwKg==
    #客户端超时时间单位是毫秒 默认是2000
    timeout: 5000
    #数据库
    database: 0
    jedis:
      pool:
        max-idle: 300
        max-active: -1
        max-wait: 5000

#  freemarker:
#    check-template-location: false
#    enabled: false


mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml


#日志
logging:
  file:
    path: E:/logs/imsystem
  level:
    root: debug

mail:
  smtp:
    host: smtp.163.com
    username: gdzqxcl@163.com
    password: imsystem666
    defaultEncoding: UTF-8
    auth: true
    timeout: 20000
    port: 465
    socketFactory:
      class: javax.net.ssl.SSLSocketFactory

# swagger
swagger:
  enable: true